version: '3.6'

services:
  backoffice:
    image: node:19.6
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command:
      - /bin/bash
      - -c
      - |
          npm install
          npm run build