version: '3'

services:
  fake-psp:
    image: node
    networks:
      - fake-psp
    env_file:
      - fake-psp/.env
    working_dir: /usr/src/app
    volumes:
      - ./fake-psp:/usr/src/app
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm run build

  api:
    image: node
    env_file:
      - payless-api/.env
    working_dir: /usr/src/app
    volumes:
      - ./payless-api:/usr/src/app
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm run build
    networks:
      - fake-psp
      - payless-network

  mongo:
    image: mongo
    networks:
      - fake-psp
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db-data:/data/db
    working_dir: /usr/local/sampleCollections

  db:
    image: postgres
    networks:
      - fake-psp
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
      POSTGRES_PORT: 5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  backoffice:
    image: node:19.6
    networks:
      - fake-psp
    working_dir: /usr/src/app
    volumes:
      - ./payless-backoffice:/usr/src/app
    command:
      - /bin/bash
      - -c
      - |
       npm install
       npm run build

networks:
  fake-psp:
    driver: bridge
  payless-network:
    external: true

volumes:
  db-data: {}
  pg-data: {}