version: '3.6'

services:
  mongo:
    ports:
      - 27017:27017
  db:
    ports:
      - 5433:5432
  server:
    ports:
      - 3000:3000
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm run dev