name: Testing

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          cp payless-api/.env.test payless-api/.env
          cp fake-psp/.env.example fake-psp/.env
          cp payless-backoffice/.env.example payless-backoffice/.env
          docker-compose up api -d --build
          docker-compose up db -d --build

      - name: Run tests with Docker Compose
        run: docker-compose run api npm test 

      - name: Tear down Docker Compose
        run: docker-compose down
