name: Testing

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Create external network
        run: |
          docker network create fake-psp
          docker network create payless-network

      - name: Set up Docker Compose
        run: |
          cp payless-api/.env.test payless-api/.env
          cp fake-psp/.env.example fake-psp/.env
          cp payless-backoffice/.env.example payless-backoffice/.env
          docker-compose up -d --build
      
      - name: Wait for servers to start
        run: sleep 30

      - name: Run tests with Docker Compose
        run: docker-compose run api npm test 

      - name: Tear down Docker Compose
        run: docker-compose down
